### ISSUE TITLE
Update tc-core-library-js version

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/legacy-challenge-processor#1]
Upgrade to https://github.com/appirio-tech/tc-core-library-js/releases/tag/v2.6.2

**Comment by rootelement** [comment]
Current version from package.json:
`"tc-core-library-js": "git+https://github.com/appirio-tech/tc-core-library-js.git#v2.6.2",`

**Comment by rootelement** [comment]
I was wrong, it's:
`"tc-core-library-js": "github:appirio-tech/tc-core-library-js.git#v2.6.1",`

@ThomasKranitsas does this need to be updated?

**Comment by rootelement** [comment]
This has been updated to 2.6.4.
