### ISSUE TITLE
Group information is not synced to legacy challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/legacy-challenge-processor#17]
When a challenge is created, via v5 api, and the challenge is associated with a group when saved as draft, it is not syncing that information to the legacy challenge as I can not see the group being set for the challenge in legacy challenge.

fyi @ThomasKranitsas @rootelement

**Comment by rootelement** [comment]
I believe this is closed. Thomas and I both tried from Postman/API and Challenge Manager and this works correctly. Please confirm if we can close this issue or if anything still remains.

**Comment by vikasrohit** [comment]
Yep we can now close it as the only other thing where it was not syncing the groups to legacy was when groups was added/updated after challenge was created in legacy which is now fixed with v4 challenge api (in dev only).
