### ISSUE TITLE
Using challenge startDate for the first phase of legacy challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/legacy-challenge-processor#19]
@ThomasKranitsas @rootelement Do you think any issue if we use the `challenge.startDate` for `registrationStartAt` field in legacy challenge at https://github.com/topcoder-platform/legacy-challenge-processor/blob/80b36c880df1de4fff7c349818de46ace2b0135a/src/services/ProcessorService.js#L160?

**Comment by ThomasKranitsas** [comment]
I think we can do that
