### ISSUE TITLE
Task assigned member is not being synced to the legacy

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/legacy-challenge-processor#24]
@ThomasKranitsas It seems like task assigned member is not being synced to the legacy challenge.

**Comment by vikasrohit** [comment]
fyi @rootelement

**Comment by ThomasKranitsas** [comment]
@rootelement this comes to the issues we were having when working on the sync tool. I'm not 100% sure how the assigned member is saved/defined on legacy. It seems that it's simply a resource (`Submitter`) which is then selected as the winner when calling `${config.V4_CHALLENGE_API_URL}/${challengeId}/close?winnerId=${winnerId}`.

The correct flow would be:
- You select the assigned member on the CM
- A resource of type `Submitter` (`732339e7-8e30-49d7-9198-cccf9451e221`) is created (by calling the Resources API through the CM)
- The legacy resource processor will create the same resource on the legacy challenge
- Once you close the task, the legacy challenge processor should detect that you closed a task and will call the `/close` endpoint to close the task on the legacy.

Let me know if I missed anything.

**Comment by vikasrohit** [comment]
Thanks @ThomasKranitsas for the details. I have couple of queries around task handling in general:

1. Why we need `isAssigned` to be set as `true` in v5 when we already set `memberId` field to the id of the assigned user and a non null `memberId` means it is assigned.
2. If we need to call the resource api to add the assigned user as submitter to the challenge, it seems we are keeping the same information at multiple places which can make things out of sync because it would be now caller responsibility to make sure `task.memberId` is set, `task.isAssigned` is set and then make sure the resource is added to the challenge as `Submitter`.
I would rather suggest that caller just sets the `task.memberId` and rest is taken care by either challenge api or some kind of challenge processor. 

Also, one query around:
> The legacy resource processor will create the same resource on the legacy challenge

It uses direct database manipulation or uses v3 api to add resource to legacy challenge? Reason I am asking is that if it is also using the api like challenge legacy processor, we would have multiple points of failure in this flow and it would require us to debug at multiple places if something goes wrong in this use case.

**Comment by vikasrohit** [comment]
@rootelement @ThomasKranitsas the flow does not work because the legacy-challenge-resource-processor is also using the v4 api which does not allow you to add/remove a registrant without submission phase being active.

**Comment by lakshmiathreya** [comment]
@vikasrohit can you give QA team access to this Repo? @lakshmiathreya @codejamtc @drasticdpk

**Comment by vikasrohit** [comment]
> @vikasrohit can you give QA team access to this Repo? @lakshmiathreya @codejamtc @drasticdpk

Done

**Comment by vikasrohit** [comment]
@ThomasKranitsas @rootelement with recent fixes around `task.*` fields while assigning member to a task, I am able to add the `Submitter` resource successfully without altering the `task.*` fields. However, I am not able to see the logs in legacy-challenge-resource-processor for consuming that event of `Submitter` resource addition. Do you know what could be the possible reason there?

**Comment by vikasrohit** [comment]
**Update:** `legacy-challenge-resource-processor` was overwhelmed because of unlimited retries of failed events which has been fixed now with https://github.com/topcoder-platform/legacy-challenge-resource-processor/pull/17 which has now enabled it to receive the event as soon as it is generated. However, it was getting SQL error, while creating resource in legacy, till yesterday.

**Comment by vikasrohit** [comment]
**Update:** After last night's fixes, it seems to be working now. Submitter resources is being added to the legacy challenge even when the challenge is not active or is not in registration phase. That removes the blocker for Assign Task - Close Task use case.

However, @rootelement @ThomasKranitsas I am seeing couple of issues after these changes:

**Comment by ThomasKranitsas** [comment]
I'm working on it

**Comment by ThomasKranitsas** [comment]
This has been fixed, right @rootelement @vikasrohit ?

**Comment by rootelement** [comment]
This is working in dev
