### ISSUE TITLE
Critical: Created By and Updated By should be user Id and not handles

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/legacy-challenge-processor#40]
It seems the new change is pushing user handles in created by and updated by in project phase tables. 
Its causing errors in our loaders and OR. 

![image (2)](https://user-images.githubusercontent.com/5771673/110599736-2c712200-81a9-11eb-8d5a-926cbe4ebd0c.png)

cc @rootelement

**Comment by ThomasKranitsas** [comment]
Fixed in: https://github.com/topcoder-platform/legacy-challenge-processor/commit/cf094f165bd5b1fa6d877125192f77b50e183f08

**Comment by ThomasKranitsas** [comment]
PR for prod release: https://github.com/topcoder-platform/legacy-challenge-processor/pull/41

**Comment by rootelement** [comment]
@RiteshTC this is deployed. Thanks for reporting!
