### ISSUE TITLE
While populating Project Info Table set the Review Feedback Flag to false

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/legacy-challenge-processor#44]
While populating the Project Info table in Informix for a challenge, set the Project Type Info Id = 59 (Review Feedback Flag) to false.
Setting the value to true, prevents the copilot payment from being generated.

<img width="1039" alt="Screen Shot 2021-03-29 at 6 16 37 PM" src="https://user-images.githubusercontent.com/5771673/112838682-f09bef00-90ba-11eb-9ffe-5b6ec5863af9.png">

**Comment by ThomasKranitsas** [comment]
Here you go: https://github.com/topcoder-platform/legacy-challenge-processor/pull/45 

cc @rootelement

**Comment by rootelement** [comment]
Deploying to prod now
