### ISSUE TITLE
Approval Phase in Tasks

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/legacy-challenge-processor#53]
Approval phases are being created for F2F tasks which is not expected and hinders the process of task closure. This has been seen in new tasks being created 

for reference: 

https://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30176589
https://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30176565

These two challenges were having approval phase , support had to explicitly remove the phases in order to close the tasks.

**Comment by rootelement** [comment]
This is fixed in prod. Please test and close this issue when you see the correct timeline.
